# Generated by Django 5.2.11 on 2026-09-18 21:14
#
# This migration deliberately describes the schema as it was BEFORE the
# RevokedCertificate model learned to cover roots and intermediates.
#
# Reason: the historical deployment never committed migrations. Its start.sh ran
# `makemigrations` at boot, which produced a migration Django named
# `0001_initial`, and recorded it in django_migrations. If this file instead
# carried the newer model state, an existing database would see 0001_initial as
# already applied, skip it, and keep the old columns -- leaving the schema out of
# step with the models. Keeping 0001 as the historical state means an upgrade
# skips it (correct, the tables already exist) and applies 0002 onwards, while a
# fresh database runs 0001 then 0002 and lands on the same final schema.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('REVOKE', 'Revoke'), ('DOWNLOAD', 'Download'), ('ACCESS', 'Access')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IntermediateCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('public_key', models.TextField()),
                ('private_key_encrypted', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intermediate_certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeafCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=255)),
                ('san', models.TextField()),
                ('valid_until', models.DateTimeField()),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('public_key', models.TextField()),
                ('private_key_encrypted', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leaf_certificates', to=settings.AUTH_USER_MODEL)),
                ('signed_by_intermediate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LocalCA.intermediatecertificate')),
            ],
        ),
        migrations.CreateModel(
            name='RootCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('public_key', models.TextField()),
                ('private_key_encrypted', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='root_certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RevokedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LocalCA.leafcertificate')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='intermediatecertificate',
            name='signed_by_root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LocalCA.rootcertificate'),
        ),
    ]
