# Generated by Django 5.2.11 on 2026-09-28 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalCA', '0002_revocation_targets_and_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intermediatecertificate',
            name='private_key_wrapped',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leafcertificate',
            name='private_key_wrapped',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rootcertificate',
            name='private_key_wrapped',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VaultRootKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrapped_root_key', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vault_root_key', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
